version: "3.8"

services:
  java_app:
    build:
      context: .
    container_name: expensesapp
    networks:
      - expenses-app-nw
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/expenses_tracker?allowPublicKeyRetrieval=true&useSSL=false"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Test@123
    depends_on:
      - mysql_db
    restart: always
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f https://localhost:8000 || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 60s 
    ports:
      - "8080:8080"
          
  mysql_db:
    image: mysql
    container_name: mysql
    networks:
      - expenses-app-nw
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: expenses_tracker
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "ping", "-h", "localhost", "-uroot", "-pTest@123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s      
    volumes:
      - ./mysql-data:/var/lib/mysql

networks:
  expenses-app-nw:
